### ISSUE TITLE
Overall planning, rewrite

### ISSUE THREAD

**Issue by swooboo** [swooboo/HERITAGE#1]
c2c3a3b477b46b2a1aff0354348708686d5cc0a6 - started from scratch. I need your help @TheLastProject. What we want to achieve in the end is a rewrite using OO principles. I've read a [JS Prototype Tutorial](http://yehudakatz.com/2011/08/12/understanding-prototypes-in-javascript/), which might help.

I'm thinking of the following objects:
- Game - will contain game mechanics
- Room - will contain room actions
- View - communicating with the user.

What do you think?

**Comment by TheLastProject** [comment]
An OO rewrite sounds like quite a good idea, HERITAGE could really use a rewrite, although I'm not quite sure about the best structure.

On the high level, HERITAGE has the following types:
- Room
- Item
- Action
- Exit
- Variable

It is important to note that items and actions are basically disconnected objects and items can be assigned to several rooms, so there is a lot of complicated referencing to do.

There are two other types, called import and info. Info would obviously be part of Game, and import should just call a function and is not an object on its own.

Currently, I'd think the following structure is best:
- Game
  - contains general game information, set with [info](https://heritage.readthedocs.org/en/latest/pages/statements.html#info).
  - contains an xyz-indexed list of rooms
  - contains a list of actions
  - contains a list of variables
- Room
  - contains a first_enter
  - contains a description
  - contains a list of items
  - contains a list of exits
  - contains a state (visited or not)
  - contains an enter function which checks the state and runs first_enter depending on the state or not and sets the player accordingly
- Item
  - contains a list of actions (this is a bit tricky, as the items are different for each instance of item)
  - contains a function to execute an action, returning a default if no such action exists
- Exit
  - contains [a lot of small substatements](https://heritage.readthedocs.org/en/latest/pages/statements.html#exit)
  - contains a function to execute which will check if all conditions are satisfied and teleport the user, returning [0, ''] on success and [1, fail message] on fail, for consistency with action
- Action
  - contains [a lot of small substatements](https://heritage.readthedocs.org/en/latest/pages/statements.html#action)
  - contains a function like Exit (maybe Exit and Action could have a similar base? The difference between the two is fairly minor)
- Var (this one is nicely simple)
  - contains a name
  - contains a value

And last, but not least,
- Player
  - contains a name
  - contains a list of items (local inventory)
  - contains an xyz location, so that we can reach the room the player is in through Game

Player plays a pretty big role and we probably want to make the player part of Game (as in, make Game contain a player), so that through Game we can also control the player's position more easily.

How does that sound to you?

**Comment by swooboo** [comment]
Sounds good. Note that I've never done JS in an OO way. (Actually a teacher of mine always insists that it's not OO.) But this seems nice. But shouldn't the rooms contain 'pointers' to other rooms for easier access, and also the player?

**Comment by swooboo** [comment]
@TheLastProject, check out [full-rewrite](https://github.com/swooboo/HERITAGE/tree/full-rewrite) branch - didn't add some entities yet, like Exit or Action, because I can't yet fully understand what they are. But I think I am in the right direction. What do you think?

**Comment by TheLastProject** [comment]
It's been a while since I did anything with HERITAGE, so it's a bit of guesswork, but it does seem right.

Exits would contain a list of conditions to check (is an item at a specific location, is an item in the player inventory, etc.) before it activates and the x, y and z coordinates to teleport the player to once activated, see https://github.com/TheLastProject/HERITAGE/blob/master/example/exits.heritage.

Actions are basically full sentences like "write note" or "put note on table", see https://github.com/TheLastProject/HERITAGE/blob/master/example/actions.heritage.

I did, however, notice a small bug in Room (should obviously be `!this.visited`):

```
this.enter = function() {
    if (this.visited)
        this.first_enter();
};
```

**Comment by swooboo** [comment]
1. Good catch, fixed the `if`.
2. So exits are basically 'teleports', because they don't follow the normal x,y,z topology?
3. I initially planned actions to be part of items, but it seems that they are a separate entity, correct? The format in the blob you gave reminds me of a material for an AI course I took, there was an algorithm for solving general real-life problems...

**Comment by TheLastProject** [comment]
Exits indeed are basically teleports. They're placed in a room with a certain name so you can call them `go north`, then the conditions are checked and if they are all satisfied you get moved to the x, y and z coordinates given in the "exit".

Originally, actions are implemented as a separate entity, because they could refer to multiple items for example (`write with pen on paper`). As far as I know, nobody ever really made HERITAGE levels so if you feel it is sane to change it a bit I'd say go ahead.

**Comment by swooboo** [comment]
Check this out - 0bb2c7de0cd0d9b3f51b4b6b3fd9a4b1b8875360, you can expand to view everything. I added the Action and the Exit classes, somewhat as you instructed, and in compliance with the examples you provided. Am I missing anything? Also note how clean the code looks...

@TheLastProject

**Comment by TheLastProject** [comment]
It's starting to look rather nice and I can't think of anything wrong with it. One thing though, seeing how this is all your code, you probably want to update the copyright header.

**Comment by swooboo** [comment]
Hmm good point. But I don't understand licenses at all, what do you mean? Should I just add my name/email to it alongside yours?

**Comment by TheLastProject** [comment]
Seeing how you literally threw all engine code away, it's most logical to just replace my name and email with yours, as you created this.

**Comment by swooboo** [comment]
Well, I completely disagree. The idea and initial execution was yours, I'm re-writing, but not creating anything new (yet). It usually is a lot easier to rewrite someone's code, make it work better and such, just because one can learn from the mistakes the original author made. And even now, I'm using your guidance actively, so you well deserve the credit. I just don't know how to correctly add this.

Now it's:

```
	Copyright (C) 2014 - 2015  SylvieLorxu <sylvie@contracode.nl>
```

Should it be something like this?
```
	Copyright (C) 2014 - 2015 
		SylvieLorxu <sylvie@contracode.nl>
		swooboo <swooboo@mail.ru>
```

**Comment by TheLastProject** [comment]
Fair enough, but in that case, please do me a favour and change it to ```Sylvia van Os <iamsylvie@openmailbox.org>``` :)

Edit: Also, 2014 - 2016 as some pretty significant changes by you were made in 2016

**Comment by swooboo** [comment]
Done - 318f760, closing this issue.
